Added dev menu, json file loading and time sync
poker-bot-battles/poker-frontend pull request #5
Opened 2023-03-10 14:29 UTC by davidfeldner

2023-03-10 17:06 UTC, lucasfth requested changes
Hvis bare print statement kan være mere deskriptivt er det perfekt for mig

2023-03-11 10:46 UTC, duckth requested changes

2023-03-11 10:46 UTC, duckth commented on poker-tournament-visualization/src/app/dev-menu/dev-menu.component.html
> +    <h3>{{activeJSON == "" ? "No active json" : "Active game: "  + activeJSON}}</h3>
Tom streng er falsie right? så ingen grund til at lave comparison, bare vend ternary'en om
Pls corrrect me if im wrong @fredpetersen 
```suggestion
    <h3>{{activeJSON ? "Active game: "  + activeJSON : "No active json"}}</h3>
```

2023-03-11 10:46 UTC, duckth commented on poker-tournament-visualization/src/app/dev-menu/dev-menu.component.html
> +    <h3 type="text">{{timestamp == "" ? "No timestamp set" : "Starting at: "  + timestamp}}</h3>
```suggestion
    <h3 type="text">{{timestamp ? "Starting at: "  + timestamp : "No timestamp set"}}</h3>
```

2023-03-11 10:46 UTC, duckth commented on poker-tournament-visualization/src/app/dev-menu/dev-menu.component.ts
> +    if (!this.jsonUrl || this.jsonUrl == "") return;
Igen, der burde ikke være nogen grun til at tjekke for tom streng hvis du alligevel spørger om den er false.
```suggestion
    if (!this.jsonUrl) return;
```

2023-03-11 10:46 UTC, duckth commented on poker-tournament-visualization/src/app/dev-menu/dev-menu.component.ts
> +    if (!this.syncUrl || this.syncUrl == "") return;
```suggestion
    if (!this.syncUrl) return;
```

2023-03-12 16:41 UTC, davidfeldner commented on poker-tournament-visualization/src/app/poker-game/new-poker-game.service.ts
> +        console.log("got new data ... ")
Helt klart, har committed nogle lidt mere beskrivende prints 👍

2023-03-12 16:44 UTC, davidfeldner commented on poker-tournament-visualization/src/app/poker-game/new-poker-game.service.ts
> +            //eller også vinder han det ved rewards? tag start af det andet game?
Ved ikke hvorfor min linter/vscode ikke synes der måtte være et mellemrum i kommentaren, men ja vi skal nok prøve at holde det engelsk. Kunne ikke lige se hvad denne kommentar referer til, så venter lige med at oversætte/slette den.

2023-03-12 18:28 UTC, lucasfth approved these changes
lgtm

2023-03-14 09:55 UTC, duckth commented
Løs konflikterne og så er vi good

2023-03-15 02:13 UTC, merged